name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -project ./Zupan-VoiceRecognition/Zupan-VoiceRecognition.xcodeproj -scheme Zupan-VoiceRecognition -destination 'name=iPhone 12' build
    - name: Test
      run: xcodebuild -project ./Zupan-VoiceRecognition/Zupan-VoiceRecognition.xcodeproj -scheme Zupan-VoiceRecognition -destination 'name=iPhone 12' test